### ISSUE TITLE
librosa > 0.10.0 not working with pyinstaller

### ISSUE THREAD

**Issue by Josef-Haupt** [librosa/librosa#1705]
My application uses librosa for audio processing and I also use pyinstaller (current version  >= 5.10.1) to bundle it.
This has been working fine before upgrading to librosa 0.10.x.

**To Reproduce**
Here is a [minimal example](https://gist.github.com/Josef-Haupt/182ec58dfcda94f6378916daecff6e3d), that works with librosa 0.9.2 but not with 0.10.x

The following exception is raised:
```
Traceback (most recent call last):
  File "run_audio.py", line 4, in <module>
  File "lazy_loader\__init__.py", line 77, in __getattr__
AttributeError: module 'librosa.core' has no attribute 'load'
```

I'm using python 3.11.2 for my minimal example, but also doesn't work with Python 3.10.10 in my main app.

I also tried updating lazy_loader, as per this [comment](https://github.com/pyinstaller/pyinstaller/issues/7489#issuecomment-1466820480), but it doesn't help.

So the current workaround is to downgrade librosa. If you need further information, feel free to ask!

**Comment by Josef-Haupt** [comment]
Thanks for tip!
I've got `lazy_loader 0.3rc0.dev0` from their main branch, which still doesn't work with the recent librosa version.

Guess I'll use the 0.9.x version for now.

**Comment by bmcfee** [comment]
> I've got `lazy_loader 0.3rc0.dev0` from their main branch, which still doesn't work with the recent librosa version.

It doesn't work with librosa?  Or it doesn't work with pyinstaller?  I'd be very surprised if lazy_loader 0.3 series suddenly breaks librosa in general.

**Comment by Josef-Haupt** [comment]
No, bad wording on my part, librosa in general works.
I just can't get the current versions of pyinstaller + librosa + lazy_loader to work together.

Gives me:
```
Traceback (most recent call last):
  File "run_audio.py", line 4, in <module>
  File "lazy_loader\__init__.py", line 77, in __getattr__
AttributeError: module 'librosa.core' has no attribute 'load'
```

**Comment by solcabz** [comment]
hi so to use librosa i must use librosa 0.9.2 not the latest version @Josef-Haupt

**Comment by achimmihca** [comment]
> the current workaround is to downgrade librosa

Confirmed. I was able to compile [basic pitch](https://github.com/spotify/basic-pitch) to an executable using pyinstaller by explicitly specifying `librosa==0.9.2` in my `requirements.txt`.

Besides the downgrade of librosa, I also had to add this extra hook from [StackOverflow](https://stackoverflow.com/a/76163556/4412885)

**Comment by bmcfee** [comment]
I think this should be resolved now if you use the pyinstaller-hooks-contrib package, which includes a recipe for librosa:

https://github.com/pyinstaller/pyinstaller-hooks-contrib

Can you give it a shot and let me know if it works?  If so, I can update the librosa documentation to make this solution easier to find.

**Comment by bmcfee** [comment]
@Josef-Haupt Following up, it looks like the 2023.4 release of pyinstaller-hooks-contrib went out a few days ago, and includes the librosa hook: https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/CHANGELOG.rst#20234-2023-06-27

I think this should be resolved now, but please try it out and let me know if there are still issues.

**Comment by XPDD** [comment]
> @Josef-Haupt接下来，看起来 pyinstaller-hooks-contrib 的 2023.4 版本几天前已经发布，并且包含 librosa hook：https: [//github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/CHANGELOG.rst#20234-2023-06-27](https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/CHANGELOG.rst#20234-2023-06-27)
> 
> 我认为现在应该解决这个问题了，但请尝试一下，如果还有问题请告诉我。

this also have this problem

**Comment by uplg** [comment]
Seems that the hook doesn't change anything, I'm on hooks-contrib latest but it doesn't work for librosa > 0.9.2

**Comment by Josef-Haupt** [comment]
We are using `0.10.2.post1` with pyinstaller `6.13.0` and pyinstaller-hooks-contrib `2025.2` and it works fine.

**Comment by uplg** [comment]
Do you have any specific config in spec files linked to librosa ? Maybe under hiddenimports to use the hook?

**Comment by Josef-Haupt** [comment]
You can check the pyinstaller output and search for librosa, there should be a line like this:
```
15352 INFO: Processing standard module hook 'hook-librosa.py' from '...\\.venv\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\stdhooks'
```
I also have "resampy" as hiddenimport, but could be outdated by now.
`lazy_loader` is at 0.4 maybe that has an impact.

**Comment by uplg** [comment]
Thanks for the help, in fact there was an other custom hook made by another developer for librosa (probably before hooks contrib), I added the hidden_import librosa and removed the custom hook and it works with librosa 0.11 and pyinstaller 6.12.0 🎉
